version: '3.8'

services:
  backend:
    build: ./backend
    container_name: birthday-backend
    restart: unless-stopped
    env_file:
    - ./backend/.env
    environment:
      NODE_ENV: production
    volumes:
      - ./backend/prisma:/app/prisma   # База + схема
      - ./backend/prisma/data:/app/prisma/data
    networks:
      - proxy
    ports:
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.birthday-backend.rule=(Host(`birthday.nologs.site`) || Host(`api.birthday.nologs.site`)) && (PathPrefix(`/api`) || PathPrefix(`/rsvp`))"
      - "traefik.http.routers.birthday-backend.entrypoints=websecure"
      - "traefik.http.routers.birthday-backend.middlewares=birthday-backend-stripprefix@file"
      - "traefik.http.services.birthday-backend.loadbalancer.server.port=3001"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: https://api.birthday.nologs.site
    container_name: birthday-frontend
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.birthday-frontend.tls=true"
      - "traefik.http.routers.birthday-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.birthday-frontend.rule=Host(`birthday.nologs.site`)"
      - "traefik.http.services.birthday-frontend.loadbalancer.server.port=80"

volumes:
  birthday-data:

networks:
  proxy:
    external: true